import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from flask import Flask, request, jsonify
from flask_cors import CORS
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import traceback

from utils.data_fetcher import get_stock_data
from utils.indicators import add_indicators

app = Flask(__name__)
# Enable CORS for frontend integration
CORS(app)

@app.route('/api/predict', methods=['POST'])
def predict():
    try:
        data = request.json
        ticker = data.get("ticker", "RELIANCE.NS")
        
        # 1. Fetch data
        df = get_stock_data(ticker)
        
        if df is None or df.empty:
            return jsonify({"error": f"No data found for ticker {ticker}"}), 404
            
        # 2. Add technical indicators
        df = add_indicators(df)
        
        # Keep a copy with dates for history
        df_history = df.copy()
        
        # Drop NaN values that are generated by rolling averages
        df = df.dropna().copy()
        
        if df.empty:
            return jsonify({"error": "Not enough data to calculate indicators"}), 400
            
        # 3. Dynamic Model Training for this specific stock
        # We want to predict tomorrow's close based on today's indicators
        df['Target'] = df['Close'].shift(-1)
        df_train = df.dropna()
        
        if len(df_train) < 10: # Need at least some valid rows
             return jsonify({"error": "Not enough training data points."}), 400
             
        X_train = df_train[['SMA_50', 'EMA_20', 'RSI']]
        y_train = df_train['Target']
        
        model = RandomForestRegressor(n_estimators=50, random_state=42)
        model.fit(X_train, y_train)

        # Get the latest row of data to make our prediction
        latest_data = df.iloc[-1]
        
        def get_val(df_row, key):
            val = df_row[key]
            if isinstance(val, pd.Series):
                return float(val.iloc[0])
            return float(val)

        current_price = get_val(latest_data, 'Close') if 'Close' in latest_data else 0.0
        sma_50 = round(get_val(latest_data, 'SMA_50'), 2)
        ema_20 = round(get_val(latest_data, 'EMA_20'), 2)
        rsi = round(get_val(latest_data, 'RSI'), 2)
        
        features = [[sma_50, ema_20, rsi]]
        prediction = model.predict(features)[0]
        
        # 4. Extract Historical Data for Charting (last 30 days)
        # yfinance index is usually Date or Datetime
        hist_subset = df_history.tail(30)
        
        dates = []
        prices = []
        for idx, row in hist_subset.iterrows():
            if hasattr(idx, 'strftime'):
                dates.append(idx.strftime('%Y-%m-%d'))
            else:
                dates.append(str(idx).split()[0])
            
            prices.append(get_val(row, 'Close'))
            
        # Add the prediction as a synthetic "T+1" date
        dates.append("Prediction")
        prices.append(round(float(prediction), 2))

        return jsonify({
            "ticker": ticker,
            "current_price": round(current_price, 2) if current_price else None,
            "prediction": round(float(prediction), 2),
            "indicators": {
                "SMA_50": round(sma_50, 2),
                "EMA_20": round(ema_20, 2),
                "RSI": round(rsi, 2)
            },
            "history": {
                "dates": dates,
                "prices": prices
            }
        })
        
    except Exception as e:
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)
